version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=powergrid
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
